const CONFIGS_RETRIEVED = 'CONFIGS_RETRIEVED';
const CONFIG_EVENTS_RETRIEVED = 'CONFIG_EVENTS_RETRIEVED';
const CONFIG_DETAILS_RETRIEVED = 'CONFIG_DETAILS_RETRIEVED';
const CONFIG_STATS_RETRIEVED = 'CONFIG_STATS_RETRIEVED';
const CONFIG_SEARCH_STRING_CHANGED = 'CONFIG_SEARCH_STRING_CHANGED';

module.exports = {
  CONFIGS_RETRIEVED,
  CONFIG_EVENTS_RETRIEVED,
  CONFIG_DETAILS_RETRIEVED,
  CONFIG_STATS_RETRIEVED,
  CONFIG_SEARCH_STRING_CHANGED,
};
