const CONTAINERS_RETRIEVED = 'CONTAINERS_RETRIEVED';
const CONTAINER_PROCESSES_RETRIEVED = 'CONTAINER_PROCESSES_RETRIEVED';
const CONTAINER_LOGS_RETRIEVED = 'CONTAINER_LOGS_RETRIEVED';
const CONTAINER_EVENTS_RETRIEVED = 'CONTAINER_EVENTS_RETRIEVED';
const CONTAINER_DETAILS_RETRIEVED = 'CONTAINER_DETAILS_RETRIEVED';
const CONTAINER_STATS_RETRIEVED = 'CONTAINER_STATS_RETRIEVED';

module.exports = {
  CONTAINERS_RETRIEVED,
  CONTAINER_PROCESSES_RETRIEVED,
  CONTAINER_LOGS_RETRIEVED,
  CONTAINER_EVENTS_RETRIEVED,
  CONTAINER_DETAILS_RETRIEVED,
  CONTAINER_STATS_RETRIEVED,
};
