const DOCKER_DAEMON_RETRIEVED = 'DOCKER_DAEMON_RETRIEVED';
const DOCKER_DAEMON_EVENTS_RETRIEVED = 'DOCKER_DAEMON_EVENTS_RETRIEVED';
const DOCKER_DAEMON_DETAILS_RETRIEVED = 'DOCKER_DAEMON_DETAILS_RETRIEVED';
const DOCKER_DAEMON_STATS_RETRIEVED = 'DOCKER_DAEMON_STATS_RETRIEVED';

module.exports = {
  DOCKER_DAEMON_RETRIEVED,
  DOCKER_DAEMON_EVENTS_RETRIEVED,
  DOCKER_DAEMON_DETAILS_RETRIEVED,
  DOCKER_DAEMON_STATS_RETRIEVED,
};
