const ABORT_EXISTING_EVENT_STREAM = 'ABORT_EXISTING_EVENT_STREAM';
const REGISTER_EVENT_STREAM = 'REGISTER_EVENT_STREAM';

module.exports = {
  ABORT_EXISTING_EVENT_STREAM,
  REGISTER_EVENT_STREAM,
};
