const ABORT_EXISTING_EVENT_STREAM = 'ABORT_EXISTING_EVENT_STREAM';
const REGISTER_EVENT_STREAM = 'REGISTER_EVENT_STREAM';
const UPDATE_SELECTED_EVENT_TYPES = 'UPDATE_SELECTED_EVENT_TYPES';
const UPDATE_FILTERED_EVENT_TYPES = 'UPDATE_FILTERED_EVENT_TYPES';

module.exports = {
  ABORT_EXISTING_EVENT_STREAM,
  REGISTER_EVENT_STREAM,
  UPDATE_SELECTED_EVENT_TYPES,
  UPDATE_FILTERED_EVENT_TYPES,
};
