const IMAGES_RETRIEVED = 'IMAGES_RETRIEVED';
const IMAGE_EVENTS_RETRIEVED = 'IMAGE_EVENTS_RETRIEVED';
const IMAGE_DETAILS_RETRIEVED = 'IMAGE_DETAILS_RETRIEVED';
const IMAGE_STATS_RETRIEVED = 'IMAGE_STATS_RETRIEVED';

module.exports = {
  IMAGES_RETRIEVED,
  IMAGE_EVENTS_RETRIEVED,
  IMAGE_DETAILS_RETRIEVED,
  IMAGE_STATS_RETRIEVED,
};
