const IMAGES_RETRIEVED = 'IMAGES_RETRIEVED';
const IMAGE_EVENTS_RETRIEVED = 'IMAGE_EVENTS_RETRIEVED';
const IMAGE_DETAILS_RETRIEVED = 'IMAGE_DETAILS_RETRIEVED';
const IMAGE_STATS_RETRIEVED = 'IMAGE_STATS_RETRIEVED';
const IMAGE_HISTORY_RETRIEVED = 'IMAGE_HISTORY_RETRIEVED';
const IMAGE_SEARCH_STRING_CHANGED = 'IMAGE_SEARCH_STRING_CHANGED';

module.exports = {
  IMAGES_RETRIEVED,
  IMAGE_EVENTS_RETRIEVED,
  IMAGE_DETAILS_RETRIEVED,
  IMAGE_STATS_RETRIEVED,
  IMAGE_HISTORY_RETRIEVED,
  IMAGE_SEARCH_STRING_CHANGED,
};
