export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL_FORM_ERROR = 'SHOW_MODAL_FORM_ERROR';
export const HIDE_MODAL_FORM_ERROR = 'HIDE_MODAL_FORM_ERROR';
export const SHOW_MODAL_NOTIFICATION = 'SHOW_MODAL_NOTIFICATION';
export const HIDE_MODAL_NOTIFICATION = 'HIDE_MODAL_NOTIFICATION';
