const NETWORKS_RETRIEVED = 'NETWORKS_RETRIEVED';
const NETWORK_EVENTS_RETRIEVED = 'NETWORK_EVENTS_RETRIEVED';
const NETWORK_DETAILS_RETRIEVED = 'NETWORK_DETAILS_RETRIEVED';
const NETWORK_STATS_RETRIEVED = 'NETWORK_STATS_RETRIEVED';
const NETWORK_SEARCH_STRING_CHANGED = 'NETWORK_SEARCH_STRING_CHANGED';

module.exports = {
  NETWORKS_RETRIEVED,
  NETWORK_EVENTS_RETRIEVED,
  NETWORK_DETAILS_RETRIEVED,
  NETWORK_STATS_RETRIEVED,
  NETWORK_SEARCH_STRING_CHANGED,
};
