const NODES_RETRIEVED = 'NODES_RETRIEVED';
const NODE_EVENTS_RETRIEVED = 'NODE_EVENTS_RETRIEVED';
const NODE_DETAILS_RETRIEVED = 'NODE_DETAILS_RETRIEVED';
const NODE_STATS_RETRIEVED = 'NODE_STATS_RETRIEVED';
const NODE_SEARCH_STRING_CHANGED = 'NODE_SEARCH_STRING_CHANGED';

module.exports = {
  NODES_RETRIEVED,
  NODE_EVENTS_RETRIEVED,
  NODE_DETAILS_RETRIEVED,
  NODE_STATS_RETRIEVED,
  NODE_SEARCH_STRING_CHANGED,
};
