const SECRETS_RETRIEVED = 'SECRETS_RETRIEVED';
const SECRET_EVENTS_RETRIEVED = 'SECRET_EVENTS_RETRIEVED';
const SECRET_DETAILS_RETRIEVED = 'SECRET_DETAILS_RETRIEVED';
const SECRET_STATS_RETRIEVED = 'SECRET_STATS_RETRIEVED';
const SECRET_SEARCH_STRING_CHANGED = 'SECRET_SEARCH_STRING_CHANGED';

module.exports = {
  SECRETS_RETRIEVED,
  SECRET_EVENTS_RETRIEVED,
  SECRET_DETAILS_RETRIEVED,
  SECRET_STATS_RETRIEVED,
  SECRET_SEARCH_STRING_CHANGED,
};
