const SERVICES_RETRIEVED = 'SERVICES_RETRIEVED';
const SERVICE_LOGS_RETRIEVED = 'SERVICE_LOGS_RETRIEVED';
const SERVICE_EVENTS_RETRIEVED = 'SERVICE_EVENTS_RETRIEVED';
const SERVICE_DETAILS_RETRIEVED = 'SERVICE_DETAILS_RETRIEVED';
const SERVICE_STATS_RETRIEVED = 'SERVICE_STATS_RETRIEVED';
const SERVICE_SEARCH_STRING_CHANGED = 'SERVICE_SEARCH_STRING_CHANGED';

module.exports = {
  SERVICES_RETRIEVED,
  SERVICE_LOGS_RETRIEVED,
  SERVICE_EVENTS_RETRIEVED,
  SERVICE_DETAILS_RETRIEVED,
  SERVICE_STATS_RETRIEVED,
  SERVICE_SEARCH_STRING_CHANGED,
};
