const VOLUMES_RETRIEVED = 'VOLUMES_RETRIEVED';
const VOLUME_EVENTS_RETRIEVED = 'VOLUME_EVENTS_RETRIEVED';
const VOLUME_DETAILS_RETRIEVED = 'VOLUME_DETAILS_RETRIEVED';
const VOLUME_STATS_RETRIEVED = 'VOLUME_STATS_RETRIEVED';

module.exports = {
  VOLUMES_RETRIEVED,
  VOLUME_EVENTS_RETRIEVED,
  VOLUME_DETAILS_RETRIEVED,
  VOLUME_STATS_RETRIEVED,
};
